# 系统用户认证模块
server:
  port: 8081  # 户认证模块端口

spring:
  application:
    name: system-service  # 注册到Eureka的服务名称

  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/deer_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 858414

  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 2  # 使用DB2存储令牌

# JWT配置
jwt:
  secret: deer-system-secret-key  # 密钥，生产环境应使用更复杂的值
  expiration: 86400  # 令牌有效期（秒）24小时
  header: Authorization  # 请求头名称
  token-prefix: Bearer   # 令牌前缀


# Eureka客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://Deer:Deer_small@localhost:8761/eureka/
    registry-fetch-interval-seconds: 5  # 获取注册表间隔
  instance:
    instance-id: ${spring.application.name}:${server.port}  # 实例ID格式
    prefer-ip-address: true  # 使用IP地址注册
    lease-renewal-interval-in-seconds: 10  # 心跳间隔
    lease-expiration-duration-in-seconds: 30  # 服务失效时间


